#! /bin/sh
#
# Main boot script for your SliTaz Embedded System
#
. /lib/libseb.sh
. /etc/seb.conf

colorize 33 "Processing /etc/init.d/rcS..."

# Mount filesystems
echo "Mounting filesystems..."
/bin/mount -a
/bin/mount --bind /run /var/run

# Populate /dev + config hotplug
echo "Population /dev and config hotplug helper..."
/bin/touch /dev/mdev.log; /sbin/mdev -s
echo "/sbin/mdev" >/proc/sys/kernel/hotplug

# Mount vdisk in Qemu or vdisk=/dev/sdb1:/path/to/sebhome.img
if blkid | fgrep -q "SebOShome"; then
	colorize 036 "Mounting seb OS virtual disk on: /home"
	mount /dev/sda /home
fi

# Parse kernel cmdline options
for opt in $(cat cmdline); do
	case "$opt" in
		home=*)
			colorize 036 "Mounting sebhome.img on: /home"
			val=${opt#home=}
			device=$(echo $val | cut -d ":" -f 1)
			path=$(echo $val | cut -d ":" -f 2)
			echo "device: $device path: $path"
			if [ -f "$path" ]; then
				mount -o loop -t ext3 ${path} /home
			else
				colorize 031 "Can't find sebhome.img virtual disk image"
			fi ;;
	esac
done

# Hostname
echo "Setting hostname to: $(colorize 033 $host_name)"
/bin/hostname ${host_name}

# Networking
/sbin/ifconfig lo 127.0.0.1 up

# Load dumped keymap
echo "Loading keyboard map..."
/sbin/loadkmap < /usr/share/kmap/default

# Source all scripts specified in config file
for script in ${run_scripts}; do
	echo $(colorize 34 "Processing: $script")
	${script}
done

echo ""
colorize 035 "Welcome to SliTaz Embedded System"
boldify "Login: root"
